{
 "title": "OPEA ChatQnA scaling",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(megaservice_request_pending,namespace)"
    }
   },
   {
    "name": "release",
    "label": "Helm release",
    "query": {
     "query": "label_values(megaservice_request_pending{namespace=\"$namespace\", service!~\".*-uservice\", service!~\".*-usvc\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Megaservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release\",namespace=\"$namespace\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(sum by (pod)(http_requests_total{method=\"POST\",service=\"$release\",namespace=\"$namespace\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Rerank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release-teirerank\",namespace=\"$namespace\"})",
     "legendFormat": "TEI instances"
    },
    {
     "expr": "count(te_queue_size{service=\"$release-teirerank\",namespace=\"$namespace\"})",
     "legendFormat": "TEI used"
    }
   ]
  },
  {
   "title": "Retrieve",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release-retriever-usvc\",namespace=\"$namespace\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(sum by (pod)(http_requests_total{method=\"POST\",service=\"$release-retriever-usvc\",namespace=\"$namespace\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Embed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release-tei\",namespace=\"$namespace\"})",
     "legendFormat": "TEI instances"
    },
    {
     "expr": "count(te_queue_size{service=\"$release-tei\",namespace=\"$namespace\"})",
     "legendFormat": "TEI used"
    }
   ]
  },
  {
   "title": "LLM-uservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release-llm-uservice\",namespace=\"$namespace\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(sum by (pod)(http_requests_total{method=\"POST\",service=\"$release-llm-uservice\",namespace=\"$namespace\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "LLM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{service=\"$release-tgi\",namespace=\"$namespace\"})",
     "legendFormat": "TGI instances"
    },
    {
     "expr": "count(tgi_queue_size{service=\"$release-tgi\",namespace=\"$namespace\"})",
     "legendFormat": "TGI used"
    },
    {
     "expr": "count(up{service=\"$release-vllm\",namespace=\"$namespace\"})",
     "legendFormat": "vLLM instances"
    },
    {
     "expr": "count(vllm:num_requests_waiting{service=\"$release-vllm\",namespace=\"$namespace\"})",
     "legendFormat": "vLLM used"
    }
   ]
  },
  { "title": "Completed requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Megaservice",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  {
   "title": "Rerank",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(te_request_count{service=\"$release-teirerank\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(te_request_count{service=\"$release-teirerank\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  {
   "title": "Retrieve",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release-retriever-usvc\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release-retriever-usvc\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  {
   "title": "Embed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(te_request_count{service=\"$release-tei\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(te_request_count{service=\"$release-tei\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  {
   "title": "LLM-uservice",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release-llm-uservice\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(http_requests_total{method=\"POST\",status=\"2xx\",service=\"$release-llm-uservice\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  {
   "title": "LLM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(sum by(pod)(rate(tgi_request_count{service=\"$release-tgi\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(tgi_request_count{service=\"$release-tgi\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    },
    {
     "expr": "max(sum by(pod)(rate(vllm:request_success_total{service=\"$release-vllm\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Most"
    },
    {
     "expr": "min(sum by(pod)(rate(vllm:request_success_total{service=\"$release-vllm\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Least"
    }
   ]
  },
  { "title": "Incomplete requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Megaservice: fail rate + pending count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service)(megaservice_request_pending{service=\"$release\",namespace=\"$namespace\"})",
     "legendFormat": "Pending total"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\",status!=\"2xx\",service=\"$release\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Failed total"
    }
   ]
  },
  {
   "title": "Rerank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(te_request_count{service=\"$release-teirerank\",namespace=\"$namespace\"}[$__rate_interval])-rate(te_request_success{service=\"$release-teirerank\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Retrieve",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\",status!=\"2xx\",service=\"$release-retriever-usvc\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Failed total"
    }
   ]
  },
  {
   "title": "Embed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(te_request_count{service=\"$release-tei\",namespace=\"$namespace\"}[$__rate_interval])-rate(te_request_success{service=\"$release-tei\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "LLM-uservice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\",status!=\"2xx\",service=\"$release-llm-uservice\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Failed total"
    }
   ]
  },
  {
   "title": "LLM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tgi_request_count{service=\"$release-tgi\",namespace=\"$namespace\"}[$__rate_interval])-rate(tgi_request_success{service=\"$release-tgi\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (err)(rate(tgi_request_failure{service=\"$release-tgi\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{err}}"
    },
    {
     "expr": "sum(vllm:num_requests_running{service=\"$release-vllm\",namespace=\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{service=\"$release-vllm\",namespace=\"$namespace\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(vllm:num_requests_swapped{service=\"$release-vllm\",namespace=\"$namespace\"})",
     "legendFormat": "Swapped to CPU"
    }
   ]
  }
 ]
}