# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "model",
    srcs = [
        "model.bin",
        "model.xml",
    ],
)
