# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatqna.fullname" . }}
  labels:
    {{- include "chatqna.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatqna.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chatqna.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: LLM_SERVICE_HOST_IP
              value: {{ .Release.Name }}-llm-uservice
            - name: RERANK_SERVICE_HOST_IP
              value: {{ .Release.Name }}-reranking-usvc
            - name: RETRIEVER_SERVICE_HOST_IP
              value: {{ .Release.Name }}-retriever-usvc
            - name: EMBEDDING_SERVICE_HOST_IP
              value: {{ .Release.Name }}-embedding-usvc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: chatqna
              containerPort: {{ .Values.port }}
              protocol: TCP
                #          startupProbe:
                #            httpGet:
                #              host: {{ .Release.Name }}-llm-uservice
                #              port: {{ index .Values "llm-uservice" "service" "port" }}
                #              path: /
                #            initialDelaySeconds: 5
                #            periodSeconds: 5
                #            failureThreshold: 120
                #          livenessProbe:
                #            httpGet:
                #              path: /
                #              port: {{ .Values.port }}
                #          readinessProbe:
                #            httpGet:
                #              path: /
                #              port: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaqna-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaqna-ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: chaqna-ui
    spec:
      containers:
      - env:
        - name: CHAT_BASE_URL
          value: "http://{{ .Values.externalIP }}:30888/v1/chatqna"
        - name: UPLOAD_FILE_BASE_URL
          value: "http://{{ .Values.externalIP }}:30452/v1/dataprep"
        image: "{{ .Values.image.uirepository }}"
        imagePullPolicy: IfNotPresent
        name: chaqna-ui
        ports:
        - containerPort: 5173
      serviceAccountName: default
