{
 "title": "tei-embedding & tei-reranking",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tei-Reranking  Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "te_queue_size{service=\"chatqna-tei\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tei-embedding  Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "te_queue_size{service=\"chatqna-tei\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGI Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tgi_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TGI Request Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tgi_request_duration_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TGI Request Queue duration sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "tgi_request_queue_duration_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TGI Request Queue duration bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tgi_request_queue_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}