#! /bin/bash

# This file was imported from https://github.com/istio/proxy at 165f759.

if [ -z "${BUILD_SCM_REVISION}" ]; then
  if git rev-parse --verify --quiet HEAD >/dev/null; then
    BUILD_SCM_REVISION="$(git rev-parse --verify HEAD)"
  else
    exit 1
  fi
fi

if [ -z "${BUILD_SCM_STATUS}" ]; then
  if git diff-index --quiet HEAD; then
    BUILD_SCM_STATUS="Clean"
  else
    BUILD_SCM_STATUS="Modified"
  fi
fi

echo "BUILD_SCM_REVISION ${BUILD_SCM_REVISION}"
echo "BUILD_SCM_STATUS ${BUILD_SCM_STATUS}"
echo "BUILD_CONFIG ${BUILD_CONFIG:-default}"
